parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: 2019
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  mocha: true

extends: ["eslint:recommended"]

rules:
  # Possible Errors
  no-await-in-loop: ["error"]
  no-console: ["warn"]
  no-extra-boolean-cast: ["error"]
  no-extra-parens: ["error", "functions"]
  no-loss-of-precision: ["error"]
  no-template-curly-in-string: ["error"]
  no-useless-backreference: ["error"]
  require-atomic-updates: ["error"]
  # Best Practices
  array-callback-return: ["error"]
  block-scoped-var: ["error"]
  consistent-return: ["error"]
  curly: ["error", "all"]
  default-case-last: ["error"]
  dot-location: ["error", "property"]
  eqeqeq: ["error", "always"]
  grouped-accessor-pairs: ["error", "setBeforeGet"]
  guard-for-in: ["error"]
  no-alert: ["error"]
  no-caller: ["error"]
  no-constructor-return: ["error"]
  no-div-regex: ["error"]
  no-else-return: ["error", {"allowElseIf": true}]
  no-empty-function: ["error"]
  no-eq-null: ["error"]
  no-eval: ["error"]
  no-extend-native: ["error"]
  no-extra-bind: ["error"]
  no-extra-label: ["error"]
  no-floating-decimal: ["error"]
  no-implied-eval: ["error"]
  no-invalid-this: ["error"]
  no-iterator: ["error"]
  no-labels: ["error"]
  no-lone-blocks: ["error"]
  no-loop-func: ["error"]
  no-multi-spaces: ["error"]
  no-multi-str: ["error"]
  no-new: ["error"]
  no-new-func: ["error"]
  no-new-wrappers: ["error"]
  no-octal-escape: ["error"]
  no-param-reassign: ["error"]
  no-proto: ["error"]
  no-return-assign: ["error"]
  no-return-await: ["error"]
  no-script-url: ["error"]
  no-self-compare: ["error"]
  no-sequences: ["error"]
  no-throw-literal: ["error"]
  no-unmodified-loop-condition: ["error"]
  no-unused-expressions: ["error"]
  no-useless-call: ["error"]
  no-useless-concat: ["error"]
  no-useless-return: ["error"]
  no-warning-comments: ["error"]
  prefer-promise-reject-errors: ["error", {"allowEmptyReject": false}]
  prefer-regex-literals: ["error"]
  radix: ["error"]
  require-await: ["error"]
  wrap-iife: ["error", "inside"]
  yoda: ["error", "never"]
  # Strict Mode
  strict: ["error", "global"]
  # Variables
  no-label-var: ["error"]
  no-restricted-globals: ["error", "event"]
  no-shadow: ["error", { "builtinGlobals": true}]
  no-undef-init: ["error"]
  no-unused-vars: ["error", {"args": "all", "argsIgnorePattern": "^_"}]
  no-use-before-define: ["error", {"functions": false, "classes": true, "variables": true}]
  # Stylistic Issues
  array-bracket-newline: ["error", "consistent"]
  array-bracket-spacing: ["error", "never"]
  block-spacing: ["error", "always"]
  brace-style: ["error"]
  camelcase: ["error"]
  comma-dangle: ["error", "only-multiline"]
  comma-spacing: ["error"]
  comma-style: ["error"]
  computed-property-spacing: ["error", "never"]
  consistent-this: ["error", "self"]
  eol-last: ["error"]
  func-call-spacing: ["error"]
  func-name-matching: ["error", "always"]
  indent: ["error", 2, {
      "SwitchCase": 1,
      "VariableDeclarator": 1,
      "MemberExpression": "off",
      "FunctionDeclaration": {"parameters": 2},
      "FunctionExpression": {"parameters": 2},
      "CallExpression": {"arguments": 2}
    }]
  jsx-quotes: ["error", "prefer-single"]
  key-spacing: ["error"]
  keyword-spacing: ["error"]
  lines-between-class-members: ["error", "always"]
  max-depth: ["error", 4]
  max-len: ["warn", {
      "code": 120,
      "ignoreStrings": false,
      "ignoreRegExpLiterals": false,
      "ignoreTemplateLiterals": true,
      "ignoreUrls": true
    }]
  max-lines: ["error", 300]
  max-nested-callbacks: ["error", 3]
  max-statements-per-line: ["error", {"max": 1}]
  new-cap: ["error", {"properties": false}]
  new-parens: ["error"]
  newline-per-chained-call: ["error", {"ignoreChainWithDepth": 2}]
  no-array-constructor: ["error"]
  no-bitwise: ["error", {"allow": ["~"]}]
  no-lonely-if: ["error"]
  no-multi-assign: ["error"]
  no-multiple-empty-lines: ["error", {"max": 2}]
  no-negated-condition: ["error"]
  no-nested-ternary: ["error"]
  no-new-object: ["error"]
  no-trailing-spaces: ["error"]
  no-unneeded-ternary: ["error"]
  no-whitespace-before-property: ["error"]
  object-curly-spacing: ["error"]
  one-var: ["error", {
      "var": "never",
      "let": "never",
      "const": "never"
    }]
  operator-linebreak: ["error", "after"]
  prefer-exponentiation-operator: ["error"]
  quotes: ["error", "single", {"allowTemplateLiterals": true}]
  quote-props: ["error", "consistent"]
  semi: ["error"]
  space-before-blocks: ["error"]
  space-before-function-paren: ["error", {
      "anonymous": "always",
      "named": "never",
      "asyncArrow": "always"
    }]
  space-in-parens: ["error", "never"]
  space-infix-ops: ["error"]
  space-unary-ops: ["error", {
      "words": true,
      "nonwords": false
    }]
  spaced-comment: ["error", "always"]
  switch-colon-spacing: ["error"]
  template-tag-spacing: ["error", "never"]
  unicode-bom: ["warn"]
  # ECMAScript 6
  arrow-body-style: ["error", "as-needed"]
  arrow-parens: ["error", "always"]
  arrow-spacing: ["error", {
      "before": true,
      "after": true
    }]
  generator-star-spacing: ["error", "after"]
  no-confusing-arrow: ["error"]
  no-duplicate-imports: ["error"]
  no-useless-computed-key: ["error"]
  no-useless-constructor: ["error"]
  no-useless-rename: ["error"]
  no-var: ["error"]
  object-shorthand: ["error", "always", {"avoidQuotes": true}]
  prefer-const: ["warn"]
  prefer-numeric-literals: ["warn"]
  prefer-rest-params: ["error"]
  prefer-spread: ["error"]
  rest-spread-spacing: ["error"]
  symbol-description: ["error"]
  template-curly-spacing: ["error", "never"]
  yield-star-spacing: ["error", "after"]

